config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  get 'home/index' => 'home#index'
  get 'home/' => 'home#index'

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role? :admin
      can :manage, :all
    elsif user.role? :user
      can [:read,:update,:destroy], User, id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_filter :authenticate_user!
  before_filter :get_user, :only => [:index, :new, :edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show, :new, :destroy, :edit, :create]

  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index
    @users = User.accessible_by(current_ability, :index)
    respond_to do |format|
      format.html
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
    end
  end
 
  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
    respond_to do |format|
      format.html
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
    end
  end
 
  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    respond_to do |format|
      format.html      
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
 
  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    respond_to do |format|
      format.html
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
 
  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy
    flash[:notice] = "User deleted."
    redirect_to(:action => :index)
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:html, :json, :xml)
  end
 
  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create
    @user = User.new(user_params)
    # authorize! :create, @user
    if @user.save
      respond_to do |format|
        format.html { redirect_to :action => :index }
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => :new, :status => :unprocessable_entity }
        format.json { render :plain => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  # PUT /users/1.json                                            HTML AND AJAX
  #----------------------------------------------------------------------------
  def update
    @user = User.find(params[:id])
    # authorize! :update, @user
    if params[:user][:password].blank?
      [:password,:password_confirmation,:current_password].collect{|p| params[:user].delete(p) }
    else
      @user.errors.add(:current_password, "The password you entered is incorrect") unless @user.valid_password?(params[:user][:current_password])
    end
    respond_to do |format|
      if @user.errors.empty? and @user.update_attributes(user_params)
        #logger.debug params[:user]
        flash[:notice] = "Your account has been updated"
        format.html { render :action => :edit }
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
      else
        format.html { render :action => :edit, :status => :unprocessable_entity }
        format.json { render :plain => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml, :html)
  end

protected

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end
 
  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end

  def user_params
    params.require(:user).permit(
                                 :email, 
                                 :password,
                                 :password_confirmation,
                                 :current_password,
                                 role_ids: []
                                 )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div>
  <span id="user-signon">
    Welcome, <%= current_user.email %><br />
    <%= link_to("Sign out", destroy_user_session_path, :method => :delete) %>
  </span>
  <% if current_user.role? :admin %>
	<span id="admin-links">
	  <%= link_to "Manage users", url_for(:controller => :users, :action => :index) %>
	</span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_errors.html.erb
<% if errors.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.errors.count, "error") %> prohibited this mark from being saved:</h2>
 
    <ul>
    <% errors.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_fields.html.erb
<p><%= f.label :email %></p>
<p><%= f.text_field :email %></p>
 
<% if can? :read, Role %>
	<p><%= f.label :role %></p>
	  <%= f.collection_check_boxes(:role_ids, Role.all, :id, :name) do |b|  %>
		 <%= b.label { b.check_box +  b.text} %><br/>
	  <% end %>

	</ul>

<% end %>

app/views/users/edit.html.erb
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>
 
<%= form_for(@user, :html => { :method => :put }) do |f| %>
	<%= render :partial => 'errors', :object => @user %>

	<%= render :partial => 'user_fields', :locals => { :f => f } %>
 
	<p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
	<p><%= f.password_field :password %></p>
 
	<p><%= f.label :password_confirmation %></p>
	<p><%= f.password_field :password_confirmation %></p>
 
	<p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
	<p><%= f.password_field :current_password %></p>
 
  <p><%= f.submit "Update" %></p>
<% end %>
<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Users</h1>
<!-- table header stuff here -->
<table cellpadding='5'>
  <tr>
    <th>Email</th>
    <th>Roles</th>
    <th>Login count</th>
    <th>Last Login</th>
    <th>Last Login IP</th>
    <% if can?(:edit, User) %>
      <th>Edit</th>
    <% end %>
    <% if can?(:delete, User) %>
      <th>Delete</th>
    <% end %>
  </tr>
  <% @users.each do |u| %>
    <tr>
      <tr class="<%= cycle('list-line-odd', 'list-line-even')-%>">
	<td><%=h u.email %></td>
	<td>
	  <% u.roles.each do |r| %>  
	    <%= r.name %>
	  <% end %>
	</td>
	<td><%=h u.sign_in_count %></td>
	<% if u.current_sign_in_at.nil? %>
	  <td>Never</td>
	<% else  %>
	  <td><%=h time_ago_in_words(u.current_sign_in_at.localtime) %> ago</td>
	<% end %>
	<td><%=h u.current_sign_in_ip %></td>
	<% if can?(:edit, User) %>
	  <td><%= link_to 'Edit', edit_user_path(u.id) %></td>
	<% end %>
	<% if can?(:delete, User) %>
	  <td><%= link_to 'Delete', u, :confirm => "Are you sure?", :method => :delete %></td>
	<% end %>
      </tr>
  <% end %>
</table>
<br/>
<% if current_user.role? :admin %>
  <span id="admin-links">
	<%= link_to 'Add', new_user_path %>
  </span>
<% end %>

app/views/users/new.html.erb
<h3>Create  User</h3>

<%= form_for(@user, :html => { :method => :post }) do |f| %>
  <%= render :partial => 'errors', :object => @user %>
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.submit "Register" %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users</h1>
<% if can?(:update, @user) %>
  <%= link_to "Edit", edit_user_path(@user) %> |
<% end %>
<% if can?(:delete, @user) %>
  <%= link_to "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete %>
<% end %>

<table class="one-column-emphasis">
  <tbody>
    <tr>
      <td class="oce-first">Email:</td>
      <td colspan='2'><%= @user.email %></td>
    </tr>
    <tr>
      <td class="oce-first">Roles:</td>
      <td  colspan='2'>
	<%= @user.roles.collect{|u| u.name}.join(", ") %>
      </td>
    </tr>
    <tr>
      <td class="oce-first">Created at:</td>
      <td colspan='2'><%= @user.created_at.localtime %></td>
    </tr>
    <tr>
      <td class="oce-first">Login Count:</td>
      <td colspan='2'><%= @user.sign_in_count %></td>
    </tr>
    <tr>
      <td class="oce-first">Last Login:</td>
      <% if @user.current_sign_in_at.nil? %>
	<td colspan='2'>Never</td>
      <% else  %>
	<td colspan='2'><%= @user.current_sign_in_at.localtime %></td>
      <% end %>
    </tr>
    <tr>
      <td class="oce-first">Last Login IP:</td>
      <td colspan='2'><%= @user.current_sign_in_ip %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back', users_path %>